"""Add user_id to Message model and relationship to User

Revision ID: b58d8acd1b0a
Revises: 5530db238e88
Create Date: 2025-04-20 01:41:20.559388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58d8acd1b0a'
down_revision: Union[str, None] = '5530db238e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - Adjust for SQLite Batch Mode ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        # Add the new column
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=False))

        # Alter existing columns for nullability
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

        # Create indexes within the batch context
        batch_op.create_index(batch_op.f('ix_messages_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_user_id'), ['user_id'], unique=False)

        # Create foreign key within the batch context (naming it is good practice)
        batch_op.create_foreign_key('fk_messages_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - Adjust for SQLite Batch Mode ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        # Drop the foreign key using the name assigned in upgrade
        batch_op.drop_constraint('fk_messages_user_id', type_='foreignkey')

        # Drop indexes
        batch_op.drop_index(batch_op.f('ix_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_project_id'))

        # Revert nullable changes
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

        # Drop the added column
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###