# schemas/project.py
from pydantic import BaseModel
from datetime import datetime
from typing import Optional

# --- Project Schemas ---

# Base properties shared by other project schemas
class ProjectBase(BaseModel):
    name: str
    description: Optional[str] = None
    context_notes: Optional[str] = None

# Properties to receive via API on creation
class ProjectCreate(ProjectBase):
    # owner_id will be set based on the authenticated user, not sent by client
    pass

# Properties properties to return via API when reading
class ProjectRead(ProjectBase):
    id: str # Include the ID generated by the DB
    owner_id: str # Include the owner's ID
    created_at: datetime
    updated_at: Optional[datetime] = None # Can be null if never updated

    class Config:
        from_attributes = True # Pydantic v2 style

# Properties to receive via API on update
class ProjectUpdate(BaseModel):
    # Make all fields optional for update
    name: Optional[str] = None
    description: Optional[str] = None
    context_notes: Optional[str] = None