name: Sync Repositories

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_SYNC_PAT }}  # Personal Access Token with repo scope

      - name: Set Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to backup repo (miktos-full)
        run: |
          # Add backup repo as a remote
          git remote add backup https://${{ secrets.REPO_SYNC_PAT }}@github.com/Miktos/miktos-full.git
          # Push to the backup repo (using the same branch name)
          git push backup ${GITHUB_REF#refs/heads/}

      - name: Prepare for public repo (miktos-api)
        run: |
          # Create a temporary branch for the public version
          git checkout -b public-temp
          
          # Remove sensitive files (environment files, credentials, etc.)
          git rm -rf --cached .env* **/secrets/ **/credentials.* **/*config.private.* || echo "No sensitive files matched patterns"
          
          # Also remove any database files and other non-public content
          git rm -rf --cached *.db *.sqlite dump.rdb || echo "No database files found"
          
          # Commit changes if there are any
          git diff --cached --quiet || git commit -m "Remove sensitive files for public repo"

      - name: Push to public API repo (miktos-api)
        run: |
          # Add public repo as a remote
          git remote add public https://${{ secrets.REPO_SYNC_PAT }}@github.com/Miktos/miktos-api.git
          # Push to the public repo (using the same branch name as the source)
          git push public public-temp:${GITHUB_REF#refs/heads/} -f