name: Sync Repositories

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get full history for proper syncing
          token: ${{ secrets.GITHUB_TOKEN }}  # Use default token

      - name: Set Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to backup repo (miktos-full)
        run: |
          echo "Adding backup repository as remote..."
          git remote add backup https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Miktos/miktos-full.git

          echo "Pushing to backup repository..."
          git push backup ${GITHUB_REF#refs/heads/} || echo "Failed to push to backup repository"

      - name: Prepare for public repo (miktos-api)
        run: |
          echo "Creating temporary branch for public version..."
          git checkout -b public-temp

          echo "Removing sensitive files..."
          # Remove sensitive files (environment files, credentials, etc.)
          git rm -rf --cached .env* **/secrets/ **/credentials.* **/*config.private.* || echo "No sensitive files matched patterns"

          # Also remove any database files and other non-public content
          git rm -rf --cached *.db *.sqlite dump.rdb || echo "No database files found"

          # Commit changes if there are any
          git diff --cached --quiet || git commit -m "Remove sensitive files for public repo"

      - name: Push to public API repo (miktos-api)
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: Miktos/miktos-api
          branch: ${GITHUB_REF#refs/heads/}
          force: true

      # Optional: Push to any other repositories if needed
      - name: Push to additional repositories
        run: |
          echo "Syncing complete. Add any additional repositories here if needed."
